
# This workflow deploys Azure automation runbooks into Azure.

name: deploying files to azure storage

on:
  push:
    branches: ["master"]
    paths:
      - "scripts/automation/**"
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: azure/login@v1
        with:
           creds: ${{ secrets.AZURE_CREDENTIALS }}

    # Upload files
      - name: Upload json to Azure Blob Storage
        id: upload
        uses: github-developer/upload-azure-blob@v1
        with:
           account: akashstg
           destination: myfile
           source: '**/*.json'

# Print out the urls to uploaded files
      - name: Print URLs
        run: echo $URLS # { ["filename":"hulatocat.png","url":"https://octodex.blob.core.windows.net/octocats/hulatocat.png"] }
        env:
          URLS: ${{ steps.upload.outputs.urls }}
 
# Logout
      - name: logout
        run: |
          az logout
