name: Upload To Azure Blob Storage
on:
  push:
    branches:
      - main
jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: LanceMcCarthy/Action-AzureBlobUpload@v2
        name: Uploading to Azure storage...
        with:
          connection_string: ${{ secrets.YourAzureBlobConnectionString }}
          container_name: myfile
          source_folder: ./agreement
